name: Vitest
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
jobs:
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install
    - name: Run tests
      run: yarn run test
    - name: Build project
      run: yarn run build
